const GUNTING = "GUNTING";
const BATU = "BATU";
const KERTAS = "KERTAS";

const PLAYER_CHOICE_LIST = [GUNTING, BATU, KERTAS];

const PLAYER_ONE = "PLAYER_ONE";
const PLAYER_TWO = "PLAYER_TWO";

const ROUND_ONE = "ROUND_ONE";
const ROUND_TWO = "ROUND_TWO";
const ROUND_THREE = "ROUND_THREE";

const WAITING_PLAYER_TWO = "WAITING_PLAYER_TWO";

const DRAW = "DRAW";
const PLAYER_ONE_WIN = "PLAYER_ONE_WIN";
const PLAYER_TWO_WIN = "PLAYER_TWO_WIN";

const DRAW_POINT = 50;
const WINNER_POINT = 100;
const LOST_POINT = 0;

module.exports = {
  GUNTING,
  BATU,
  KERTAS,
  PLAYER_ONE,
  PLAYER_TWO,
  PLAYER_CHOICE_LIST,
  ROUND_ONE,
  ROUND_TWO,
  ROUND_THREE,
  WAITING_PLAYER_TWO,
  DRAW,
  PLAYER_TWO_WIN,
  PLAYER_ONE_WIN,
  DRAW_POINT,
  WINNER_POINT,
  LOST_POINT,
};
